/**
 * BL-AIX Phase 1b — a prompt never changes without its version.
 *
 * Every prompted feature's prompts are rendered from fixed fixtures
 * (tests/ai/prompt-fixtures.ts), with the quoted-material rule the
 * gateway appends and the output schemas its structured calls send, and
 * hashed. prompt-versions.lock.json records the
 * version and hash per feature. A hash that moves while the version in
 * src/lib/ai-prompt-versions.ts stays put fails: bump the version.
 *
 * After bumping, refresh the lock:
 *   UPDATE_PROMPT_LOCK=1 npx vitest run tests/ai/prompt-versions.test.ts
 * The update rewrites only entries whose version moved; it never
 * records a new hash under an old version.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { zodToToolSchema } from "@/lib/ai";
import { AI_FEATURES } from "@/lib/ai-features";
import { PROMPT_VERSIONS, promptVersionFor, type PromptedFeature } from "@/lib/ai-prompt-versions";
import { withUntrustedContentRule } from "@/lib/prompt-safety";
import { PROMPT_RENDERERS, PROMPT_SCHEMAS } from "./prompt-fixtures";

type LockEntry = { version: string; sha256: string };
type Lock = { note: string; features: Record<string, LockEntry> };

const LOCK_PATH = path.resolve(__dirname, "prompt-versions.lock.json");
const UPDATE = process.env.UPDATE_PROMPT_LOCK === "1";
const NOTE =
  "Generated by tests/ai/prompt-versions.test.ts. Bump the feature's version in src/lib/ai-prompt-versions.ts, then run UPDATE_PROMPT_LOCK=1 npx vitest run tests/ai/prompt-versions.test.ts.";

const features = Object.keys(PROMPT_VERSIONS).sort() as PromptedFeature[];

function hashFeature(feature: PromptedFeature): string {
  const prompts = PROMPT_RENDERERS[feature]().map((p) => ({ system: withUntrustedContentRule(p.system), messages: p.messages }));
  const schemas = PROMPT_SCHEMAS[feature].map((s) => zodToToolSchema(s));
  return createHash("sha256").update(JSON.stringify({ prompts, schemas })).digest("hex");
}

function readLock(): Lock {
  try {
    return JSON.parse(readFileSync(LOCK_PATH, "utf8")) as Lock;
  } catch {
    return { note: NOTE, features: {} };
  }
}

describe("BL-AIX Phase 1b — prompt versions", () => {
  it("gives every feature that sends a prompt a version and a fixture", () => {
    const prompted = Object.keys(AI_FEATURES).filter((f) => f !== "embedding" && f !== "embedding_query").sort();
    expect(features).toEqual(prompted);
    expect(Object.keys(PROMPT_RENDERERS).sort()).toEqual(prompted);
    expect(Object.keys(PROMPT_SCHEMAS).sort()).toEqual(prompted);
    for (const f of features) {
      expect(PROMPT_VERSIONS[f], f).toMatch(/\S/);
      expect(PROMPT_RENDERERS[f]().length, f).toBeGreaterThan(0);
    }
  });

  it("falls back to an empty version for embeddings, which send no prompt", () => {
    expect(promptVersionFor("section_chat")).toBe(PROMPT_VERSIONS.section_chat);
    expect(promptVersionFor("embedding")).toBe("");
  });

  it("renders the same prompt twice (fixtures are deterministic)", () => {
    for (const f of features) expect(hashFeature(f), f).toBe(hashFeature(f));
  });

  it("never changes a prompt without bumping its version", () => {
    const lock = readLock();
    const unbumped: string[] = [];
    const stale: string[] = [];
    const next: Record<string, LockEntry> = {};

    for (const f of features) {
      const current = { version: PROMPT_VERSIONS[f], sha256: hashFeature(f) };
      const locked = lock.features[f];
      if (locked && locked.version === current.version && locked.sha256 !== current.sha256) {
        unbumped.push(`${f}: the prompt changed but its version is still ${current.version}. Bump PROMPT_VERSIONS.${f}.`);
        next[f] = locked;
      } else {
        if (!locked || locked.version !== current.version) stale.push(f);
        next[f] = current;
      }
    }
    const removed = Object.keys(lock.features).filter((f) => !(f in PROMPT_VERSIONS));

    if (UPDATE && (stale.length > 0 || removed.length > 0)) {
      writeFileSync(LOCK_PATH, `${JSON.stringify({ note: NOTE, features: next }, null, 2)}\n`);
    }

    expect(unbumped, unbumped.join("\n")).toEqual([]);
    if (!UPDATE) {
      expect(
        [...stale, ...removed],
        `prompt-versions.lock.json is out of date for: ${[...stale, ...removed].join(", ")}. Run UPDATE_PROMPT_LOCK=1 npx vitest run tests/ai/prompt-versions.test.ts`,
      ).toEqual([]);
    }
  });
});
